stages:
  - test
  - build

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: gradle-cache
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

test:
  stage: test
  image: gradle:8.0-jdk17
  script:
    - chmod +x gradlew
    - ./gradlew test
  only:
    - main

build:
  stage: build
  image: gradle:8.0-jdk17
  script:
    - chmod +x gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
  only:
    - main
