stages:
  - build
  - test
  - deploy

# Строим проект
build_job:
  stage: build
  image: gradle:7.4-jdk11
  script:
    - gradle clean assembleRelease --stacktrace --info  # Запуск с подробной информацией
  artifacts:
    paths:
      - app/build/outputs/apk/
    expire_in: 1 hour

# Тестируем проект
test_job:
  stage: test
  image: gradle:7.4-jdk11
  script:
    - gradle test --stacktrace --info  # Запуск с подробной информацией

# Деплой проекта
deploy_job:
  stage: deploy
  script:
    - echo "Deploying APK..."
  only:
    - main
