stages:
  - build
  - test

# Сборка проекта
build_job:
  stage: build
  image: gradle:7.4-jdk11  # Образ с Gradle и JDK 11
  before_script:
    - gradle wrapper --gradle-version 7.4  # Обновляем wrapper до нужной версии
    - ./gradlew --version  # Проверка версии Gradle, которая будет использоваться
  script:
    - ./gradlew clean build  # Используем gradlew, чтобы гарантировать использование версии, заданной в проекте
  artifacts:
    paths:
      - app/build/outputs  # Сохраняем результаты сборки (APK или AAB)

# Тестирование
test_job:
  stage: test
  image: gradle:7.4-jdk11  # Снова используем тот же образ
  before_script:
    - gradle wrapper --gradle-version 7.4  # Обновляем wrapper до нужной версии
    - ./gradlew --version  # Проверка версии Gradle, которая будет использоваться
  script:
    - ./gradlew test  # Запуск юнит-тестов
