stages:
  - build
  - test

variables:
  ANDROID_SDK_ROOT: "$HOME/android-sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  # Установка Android SDK, если его нет
  - if [ ! -d "$ANDROID_SDK_ROOT" ]; then
      mkdir -p "$ANDROID_SDK_ROOT";
      wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip;
      unzip commandlinetools.zip -d "$ANDROID_SDK_ROOT";
      yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-35" "build-tools;35.0.0" "platform-tools";
    fi
  - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
  - chmod +x gradlew

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/
    - app/build/

build:
  stage: build
  script:
    - ./gradlew clean assembleDebug

test:
  stage: test
  script:
    - ./gradlew testDebug
