stages:
  - build
  - test

# Сборка проекта
build_job:
  stage: build
  image: gradle:7.4-jdk11  # Используем образ с Gradle и JDK 11
  before_script:
    - gradle --version  # Проверка версии Gradle
  script:
    - gradle clean build  # Чистим и строим проект
  artifacts:
    paths:
      - app/build/outputs  # Сохраняем результаты сборки (APK или AAB)

# Тестирование
test_job:
  stage: test
  image: gradle:7.4-jdk11  # Снова используем тот же образ
  before_script:
    - gradle --version  # Проверка версии Gradle
  script:
    - gradle test  # Запуск юнит-тестов
