image: ubuntu:latest

stages:
  - build
  - test
  - deploy

before_script:
  # Установка зависимостей для Ubuntu
  - apt-get update -qq
  - apt-get install -y wget tar openjdk-11-jdk

  # Установка Android SDK
  - if [ ! -d "$ANDROID_SDK_ROOT" ]; then
      mkdir -p "$ANDROID_SDK_ROOT";
      wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip;
      unzip commandlinetools.zip -d "$ANDROID_SDK_ROOT";
      yes | $ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-35" "build-tools;35.0.0" "platform-tools";
    fi
  - export PATH="$ANDROID_SDK_ROOT/cmdline-tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
  - chmod +x gradlew

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/
    - app/build/

build:
  stage: build
  script:
    - ./gradlew clean assembleDebug

test:
  stage: test
  script:
    - ./gradlew testDebug

deploy:
  stage: deploy
  script:
    - echo "Deploying the app..."
