stages:
  - build
  - test
  - deploy

# Очистка кэша и сборка
build_job:
  stage: build
  image: gradle:7.4-jdk11
  before_script:
    - gradle clean
  script:
    - gradle assembleRelease --info --stacktrace
  artifacts:
    paths:
      - app/build/outputs/apk/
    expire_in: 1 hour

# Тестирование
test_job:
  stage: test
  image: gradle:7.4-jdk11
  script:
    - gradle test --info --stacktrace
